import mongoose from "mongoose";

const getTeams = (arenaMap: Record<string, mongoose.Types.ObjectId>) => [
  {
    name: "Hawks",
    city: "Atlanta",
    abbreviation: "ATL",
    conference: "East" as const,
    division: "Southeast",
    colors: ["#E03A3E", "#C1D32F"],
    logo: "",
    arena: arenaMap["State Farm Arena"],
    externalId: 1,
  },
  {
    name: "Celtics",
    city: "Boston",
    abbreviation: "BOS",
    conference: "East" as const,
    division: "Atlantic",
    colors: ["#007A33", "#BA9653"],
    logo: "",
    arena: arenaMap["TD Garden"],
    externalId: 2,
  },
  {
    name: "Nets",
    city: "Brooklyn",
    abbreviation: "BKN",
    conference: "East" as const,
    division: "Atlantic",
    colors: ["#000000", "#FFFFFF"],
    logo: "",
    arena: arenaMap["Barclays Center"],
    externalId: 3,
  },
  {
    name: "Hornets",
    city: "Charlotte",
    abbreviation: "CHA",
    conference: "East" as const,
    division: "Southeast",
    colors: ["#1D1160", "#00788C"],
    logo: "",
    arena: arenaMap["Spectrum Center"],
    externalId: 4,
  },
  {
    name: "Bulls",
    city: "Chicago",
    abbreviation: "CHI",
    conference: "East" as const,
    division: "Central",
    colors: ["#CE1141", "#000000"],
    logo: "",
    arena: arenaMap["United Center"],
    externalId: 5,
  },
  {
    name: "Cavaliers",
    city: "Cleveland",
    abbreviation: "CLE",
    conference: "East" as const,
    division: "Central",
    colors: ["#860038", "#FDBB30"],
    logo: "",
    arena: arenaMap["Rocket Mortgage FieldHouse"],
    externalId: 6,
  },
  {
    name: "Mavericks",
    city: "Dallas",
    abbreviation: "DAL",
    conference: "West" as const,
    division: "Southwest",
    colors: ["#00538C", "#002F5F"],
    logo: "",
    arena: arenaMap["American Airlines Center"],
    externalId: 7,
  },
  {
    name: "Nuggets",
    city: "Denver",
    abbreviation: "DEN",
    conference: "West" as const,
    division: "Northwest",
    colors: ["#0E2240", "#FEC524"],
    logo: "",
    arena: arenaMap["Ball Arena"],
    externalId: 8,
  },
  {
    name: "Pistons",
    city: "Detroit",
    abbreviation: "DET",
    conference: "East" as const,
    division: "Central",
    colors: ["#C8102E", "#006BB6"],
    logo: "",
    arena: arenaMap["Little Caesars Arena"],
    externalId: 9,
  },
  {
    name: "Warriors",
    city: "Golden State",
    abbreviation: "GSW",
    conference: "West" as const,
    division: "Pacific",
    colors: ["#1D428A", "#FFC72C"],
    logo: "",
    arena: arenaMap["Chase Center"],
    externalId: 10,
  },
  {
    name: "Rockets",
    city: "Houston",
    abbreviation: "HOU",
    conference: "West" as const,
    division: "Southwest",
    colors: ["#CE1141", "#000000"],
    logo: "",
    arena: arenaMap["Toyota Center"],
    externalId: 11,
  },
  {
    name: "Pacers",
    city: "Indiana",
    abbreviation: "IND",
    conference: "East" as const,
    division: "Central",
    colors: ["#002D62", "#FDBB30"],
    logo: "",
    arena: arenaMap["Gainbridge Fieldhouse"],
    externalId: 12,
  },
  {
    name: "Clippers",
    city: "Los Angeles",
    abbreviation: "LAC",
    conference: "West" as const,
    division: "Pacific",
    colors: ["#C8102E", "#1D428A"],
    logo: "",
    arena: arenaMap["Intuit Dome"],
    externalId: 13,
  },
  {
    name: "Lakers",
    city: "Los Angeles",
    abbreviation: "LAL",
    conference: "West" as const,
    division: "Pacific",
    colors: ["#552583", "#FDB927"],
    logo: "",
    arena: arenaMap["Crypto.com Arena"],
    externalId: 14,
  },
  {
    name: "Grizzlies",
    city: "Memphis",
    abbreviation: "MEM",
    conference: "West" as const,
    division: "Southwest",
    colors: ["#5D76A9", "#12173F"],
    logo: "",
    arena: arenaMap["FedExForum"],
    externalId: 15,
  },
  {
    name: "Heat",
    city: "Miami",
    abbreviation: "MIA",
    conference: "East" as const,
    division: "Southeast",
    colors: ["#98002E", "#F9A01B"],
    logo: "",
    arena: arenaMap["Kaseya Center"],
    externalId: 16,
  },
  {
    name: "Bucks",
    city: "Milwaukee",
    abbreviation: "MIL",
    conference: "East" as const,
    division: "Central",
    colors: ["#00471B", "#EEE1C6"],
    logo: "",
    arena: arenaMap["Fiserv Forum"],
    externalId: 17,
  },
  {
    name: "Timberwolves",
    city: "Minnesota",
    abbreviation: "MIN",
    conference: "West" as const,
    division: "Northwest",
    colors: ["#0C2340", "#236192"],
    logo: "",
    arena: arenaMap["Target Center"],
    externalId: 18,
  },
  {
    name: "Pelicans",
    city: "New Orleans",
    abbreviation: "NOP",
    conference: "West" as const,
    division: "Southwest",
    colors: ["#0C2340", "#C8102E"],
    logo: "",
    arena: arenaMap["Smoothie King Center"],
    externalId: 19,
  },
  {
    name: "Knicks",
    city: "New York",
    abbreviation: "NYK",
    conference: "East" as const,
    division: "Atlantic",
    colors: ["#006BB6", "#F58426"],
    logo: "",
    arena: arenaMap["Madison Square Garden"],
    externalId: 20,
  },
  {
    name: "Thunder",
    city: "Oklahoma City",
    abbreviation: "OKC",
    conference: "West" as const,
    division: "Northwest",
    colors: ["#007AC1", "#EF3B24"],
    logo: "",
    arena: arenaMap["Paycom Center"],
    externalId: 21,
  },
  {
    name: "Magic",
    city: "Orlando",
    abbreviation: "ORL",
    conference: "East" as const,
    division: "Southeast",
    colors: ["#0077C0", "#C4CED4"],
    logo: "",
    arena: arenaMap["Amway Center"],
    externalId: 22,
  },
  {
    name: "Sixers",
    city: "Philadelphia",
    abbreviation: "PHI",
    conference: "East" as const,
    division: "Atlantic",
    colors: ["#006BB6", "#ED174C"],
    logo: "",
    arena: arenaMap["Wells Fargo Center"],
    externalId: 23,
  },
  {
    name: "Suns",
    city: "Phoenix",
    abbreviation: "PHX",
    conference: "West" as const,
    division: "Pacific",
    colors: ["#1D1160", "#E56020"],
    logo: "",
    arena: arenaMap["Footprint Center"],
    externalId: 24,
  },
  {
    name: "Trail Blazers",
    city: "Portland",
    abbreviation: "POR",
    conference: "West" as const,
    division: "Northwest",
    colors: ["#E03A3E", "#000000"],
    logo: "",
    arena: arenaMap["Moda Center"],
    externalId: 25,
  },
  {
    name: "Kings",
    city: "Sacramento",
    abbreviation: "SAC",
    conference: "West" as const,
    division: "Pacific",
    colors: ["#5A2D81", "#63727A"],
    logo: "",
    arena: arenaMap["Golden 1 Center"],
    externalId: 26,
  },
  {
    name: "Spurs",
    city: "San Antonio",
    abbreviation: "SAS",
    conference: "West" as const,
    division: "Southwest",
    colors: ["#C4CED4", "#000000"],
    logo: "",
    arena: arenaMap["Frost Bank Center"],
    externalId: 27,
  },
  {
    name: "Raptors",
    city: "Toronto",
    abbreviation: "TOR",
    conference: "East" as const,
    division: "Atlantic",
    colors: ["#CE1141", "#000000"],
    logo: "",
    arena: arenaMap["Scotiabank Arena"],
    externalId: 28,
  },
  {
    name: "Jazz",
    city: "Utah",
    abbreviation: "UTAH",
    conference: "West" as const,
    division: "Northwest",
    colors: ["#002B5C", "#00471B"],
    logo: "",
    arena: arenaMap["Delta Center"],
    externalId: 29,
  },
  {
    name: "Wizards",
    city: "Washington",
    abbreviation: "WAS",
    conference: "East" as const,
    division: "Southeast",
    colors: ["#002B5C", "#E31837"],
    logo: "",
    arena: arenaMap["Capital One Arena"],
    externalId: 30,
  },
];

export default getTeams;
